
CREATE TABLE `langs` (
  `id` int(11) NOT NULL,
  `lang_key` varchar(160) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` varchar(100) NOT NULL DEFAULT '',
  `english` text DEFAULT NULL,
  `arabic` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `dutch` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `french` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `german` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `russian` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `spanish` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `turkish` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `thai` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `burmese` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `lao` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `khmer` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `malay` text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `langs` (`id`, `lang_key`, `type`, `english`, `arabic`, `dutch`, `french`, `german`, `russian`, `spanish`, `turkish`, `thai`, `burmese`, `lao`, `khmer`, `malay`) VALUES
(1, 'login', '', 'Login', 'تسجيل الدخول', 'Log in', 'S\'identifier', 'Anmeldung', 'Авторизоваться', 'Iniciar sesión', 'Oturum aç', 'เข้าสู่ระบบ', 'ဝင်ရောက်ပါ။', 'ເຂົ້າສູ່ລະບົບ', 'ចូលគណនី', 'Log masuk'),
(2, 'search_keyword', '', 'Search for videos', 'البحث عن مقاطع الفيديو', 'Zoek naar video\'s', 'Rechercher des vidéos', 'Suche nach Videos', 'Поиск видео', 'Buscar videos', 'Videoları arayın', 'ค้นหาวิดีโอ', 'ဗီဒီယိုများ ရှာဖွေပါ။', 'ຊອກຫາວິດີໂອ', 'ស្វែងរកវីដេអូ', 'Cari video'),
(3, 'register', '', 'Register', 'تسجيل', 'Registreren', 'registre', 'Neu registrieren', 'регистр', 'Registro', 'Kayıt olmak', 'ลงทะเบียน', 'မှတ်ပုံတင်ပါ။', 'ລົງທະບຽນ', 'ចុះឈ្មោះ', 'Daftar'),
(4, 'invalid_request', '', 'Invalid request', 'طلب غير صالح', 'Ongeldig verzoek', 'Requête invalide', 'Ungültige Anfrage', 'Неверный запрос', 'Solicitud no válida', 'Geçersiz istek', 'คำขอไม่ถูกต้อง', 'တရားမဝင် တောင်းဆိုမှု', 'ຄຳຂໍບໍ່ຖືກຕ້ອງ', 'សំណើមិនត្រឹមត្រូវ', 'Permintaan tidak sah'),
(5, 'please_check_details', '', 'Please check the details', 'يرجى التحقق من التفاصيل', 'Controleer de details', 'Vérifiez les détails', 'Bitte überprüfen Sie die Details', 'Пожалуйста, проверьте детали', 'Por favor verifique los detalles', 'Lütfen ayrıntıları kontrol edin', 'โปรดตรวจสอบรายละเอียด', 'အသေးစိတ်အချက်အလက်များ စစ်ဆေးပါ။', 'ກະລຸນາກວດສອບລາຍລະອຽດ', 'សូមពិនិត្យមើលព័ត៌មានលម្អិត', 'Sila semak butiran'),
(6, 'email_sent', '', 'E-mail sent successfully', 'تم إرسال البريد الإلكتروني بنجاح', 'E-mail is succesvol verzonden', 'E-mail envoyé avec succès', 'Email wurde erfolgreich Versendet', 'Письмо успешно отправлено', 'E-mail enviado correctamente', 'E-posta başarıyla gönderildi', 'ส่งอีเมลสำเร็จแล้ว', 'အီးမေးလ်ကို အောင်မြင်စွာ ပို့ပြီးပါပြီ။', 'ສົ່ງອີເມວສຳເລັດແລ້ວ', 'អ៊ីមែលបានផ្ញើដោយជោគជ័យ', 'E-mel berjaya dihantar'),
(7, 'email_not_exist', '', 'E-mail not exist', 'البريد الإلكتروني غير موجود', 'E-mail bestaat niet', 'E-mail n\'existe pas', 'E-Mail existiert nicht', 'Электронная почта не существует', 'E-mail no existe', 'E-posta yok', 'อีเมลไม่มีอยู่ในระบบ', 'အီးမေးလ် မရှိပါ။', 'ອີເມວບໍ່ມີໃນລະບົບ', 'អ៊ីមែលមិនមាន', 'E-mel tidak wujud'),
(8, 'reset_password', '', 'Reset Password', 'إعادة تعيين كلمة المرور', 'Wachtwoord opnieuw instellen', 'réinitialiser le mot de passe', 'Passwort zurücksetzen', 'Сброс пароля', 'Restablecer la contraseña', 'Şifreyi yenile', 'รีเซ็ตรหัสผ่าน', 'စကားဝှက်ကို ပြန်လည်သတ်မှတ်ပါ။', 'ຣີເຊັດລະຫັດຜ່ານ', 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ', 'Tetapkan semula kata laluan'),
(9, 'account_is_not_active', '', 'Your account is not active yet, please confirm your E-mail.', 'حسابك غير نشط حتى الآن، يرجى تأكيد بريدك الإلكتروني.', 'Uw account is nog niet actief, bevestig alstublieft uw e-mail.', 'Votre compte n\'est pas encore actif, confirmez votre e-mail.', 'Ihr Konto ist noch nicht aktiv, bitte bestätigen Sie Ihre E-Mail.', 'Ваша учетная запись еще не активирована, пожалуйста, подтвердите свой E-mail.', 'Su cuenta aún no está activa, por favor confirme su E-mail.', 'Hesabınız henüz aktif değil, lütfen e-postanızı onaylayın.', 'บัญชีของคุณยังไม่เปิดใช้งาน โปรดยืนยันอีเมลของคุณ', 'သင်၏အကောင့်သည် ယခုအထိ အသက်မဝင်သေးပါ။ သင့်အီးမေးလ်ကို အတည်ပြုပါ။', 'ບັນຊີຂອງທ່ານຍັງບໍ່ທັນເປີດນຳໃຊ້ເທື່ອ, ກະລຸນາຢືນຢັນອີເມວຂອງທ່ານ.', 'គណនីរបស់អ្នកមិនទាន់ដំណើរការនៅឡើយទេ សូមបញ្ជាក់អ៊ីមែលរបស់អ្នក។', 'Akaun anda belum aktif lagi, sila sahkan e-mel anda.'),
(10, 'resend_email', '', 'Resend E-mail', 'إعادة إرسال البريد الإلكتروني', 'Email opnieuw verzenden', 'Ré-envoyer l\'email', 'E-Mail zurücksenden', 'Повторно отправить E-mail', 'Reenviar email', 'Elektronik postayı tekrar gönder', 'ส่งอีเมลอีกครั้ง', 'အီးမေးလ်ကို ထပ်မံပေးပို့ပါ။', 'ສົ່ງອີເມວຄືນໃໝ່', 'ផ្ញើអ៊ីមែលសារជាថ្មី', 'Hantar e-mel semula'),
(11, 'invalid_username_or_password', '', 'Invalid username or password', 'خطأ في اسم المستخدم أو كلمة مرور', 'ongeldige gebruikersnaam of wachtwoord', 'Nom d\'utilisateur ou mot de passe invalide', 'ungültiger Benutzername oder Passwort', 'неправильное имя пользователя или пароль', 'usuario o contraseña invalido', 'Geçersiz kullanıcı adı veya şifre', 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง', 'တရားမဝင် အသုံးပြုသူအမည် သို့မဟုတ် စကားဝှက်', 'ຊື່ຜູ້ໃຊ້ ຫຼື ລະຫັດຜ່ານບໍ່ຖືກຕ້ອງ', 'ឈ្មោះអ្នកប្រើប្រាស់ ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ', 'Nama pengguna atau kata laluan tidak sah'),
(12, 'gender', '', 'Gender', 'جنس', 'Geslacht', 'Le genre', 'Geschlecht', 'Пол', 'Género', 'Cinsiyet', 'เพศ', 'ကျား/မ', 'ເພດ', 'ភេទ', 'Jantina'),
(13, 'gender_is_invalid', '', 'Gender is invalid', 'الجنس غير صالح', 'Geslacht is ongeldig', 'Le sexe n\'est pas valable', 'Geschlecht ist ungültig', 'Пол недействителен', 'Género no válido', 'Cinsiyet geçersiz', 'เพศไม่ถูกต้อง', 'ကျား/မ မှားယွင်းနေပါသည်', 'ເພດບໍ່ຖືກຕ້ອງ', 'ភេទមិនត្រឹមត្រូវ', 'Jantina tidak sah'),
(14, 'country', '', 'Country', 'بلد', 'land', 'Pays', 'Land', 'Страна', 'País', 'ülke', 'ประเทศ', 'နိုင်ငံ', 'ປະເທດ', 'ប្រទេស', 'Negara'),
(15, 'username_is_taken', '', 'Username is taken', 'اسم المستخدم ماخوذ', 'Gebruikersnaam is in gebruik', 'Le nom d\'utilisateur est pris', 'Benutzername ist vergeben', 'Имя пользователя', 'El nombre de usuario se ha tomado', 'kullanıcı adı alınmış', 'ชื่อผู้ใช้นี้ถูกใช้แล้ว', 'အသုံးပြုသူအမည်ကို ယူပြီးပါပြီ', 'ຊື່ຜູ້ໃຊ້ນີ້ຖືກນຳໃຊ້ແລ້ວ', 'ឈ្មោះអ្នកប្រើប្រាស់នេះត្រូវបានគេយកហើយ', 'Nama pengguna telah diambil'),
(16, 'username_characters_length', '', 'Username must be between 5 / 32', 'يجب أن يكون اسم المستخدم بين 5/32', 'Gebruikersnaam moet tussen 5/32 zijn', 'Le nom d\'utilisateur doit être compris entre 5/32', 'Benutzername muss zwischen 5/32 liegen', 'Имя пользователя должно быть от 5/32', 'El nombre de usuario debe estar entre 5/32', 'Kullanıcı adı 5/32 arasında olmalıdır', 'ชื่อผู้ใช้ต้องมีความยาวระหว่าง 5 ถึง 32 ตัวอักษร', 'အသုံးပြုသူအမည်သည် ၅/၃၂ ကြားတွင် ရှိရမည်', 'ຊື່ຜູ້ໃຊ້ຕ້ອງມີຄວາມຍາວລະຫວ່າງ 5 ຫາ 32 ຕົວອັກສອນ', 'ឈ្មោះអ្នកប្រើប្រាស់ត្រូវតែមានចន្លោះពី 5 ទៅ 32', 'Nama pengguna mestilah antara 5 hingga 32'),
(17, 'username_invalid_characters', '', 'Invalid username characters', 'أحرف اسم المستخدم غير صالحة', 'Ongeldige gebruikersnaam karakters', 'Caractères d\'identifiant non valides', 'Ungültige Benutzernamen', 'Неверные символы имени пользователя', 'Caracteres de usuario no válidos', 'Geçersiz kullanıcı adı karakterleri', 'ชื่อผู้ใช้มีตัวอักษรที่ไม่ถูกต้อง', 'တရားမဝင် အသုံးပြုသူအမည် စာလုံးများ', 'ຊື່ຜູ້ໃຊ້ມີຕົວອັກສອນທີ່ບໍ່ຖືກຕ້ອງ', 'ឈ្មោះអ្នកប្រើប្រាស់មានតួអក្សរមិនត្រឹមត្រូវ', 'Aksara nama pengguna tidak sah'),
(18, 'email_exists', '', 'This e-mail is already in use', 'هذا البريد استخدم من قبل', 'Deze email is al in gebruik', 'Cet e-mail est déjà utilisée', 'Diese E-Mail-Adresse wird schon verwendet', 'Этот электронный адрес уже используется', 'Este correo electrónico ya está en uso', 'Bu e-posta zaten kullanılıyor', 'อีเมลนี้ถูกใช้งานแล้ว', 'ဤအီးမေးလ်ကို အသုံးပြုပြီးပါပြီ', 'ອີເມວນີ້ຖືກນຳໃຊ້ແລ້ວ', 'អ៊ីមែលនេះកំពុងប្រើប្រាស់ហើយ', 'E-mel ini sudah digunakan'),
(19, 'email_invalid_characters', '', 'E-mail is invalid', 'البريد الإلكتروني غير صالح', 'Email is ongeldig', 'Le courriel est invalide', 'E-Mail ist ungültig', 'Недействительный адрес электронной почты', 'El correo electrónico es invalido', 'E-posta geçersiz', 'อีเมลไม่ถูกต้อง', 'အီးမေးလ် မှားယွင်းနေပါသည်', 'ອີເມວບໍ່ຖືກຕ້ອງ', 'អ៊ីមែលមិនត្រឹមត្រូវ', 'E-mel tidak sah'),
(20, 'password_not_match', '', 'Password not match', 'كلمة المرور غير متطابقة', 'Wachtwoord niet overeenkomen', 'Le mot de passe ne correspond pas', 'Passwort nicht übereinstimmen', 'Пароль не соответствует', 'La contraseña no coincide', 'Şifre eşleşmiyor', 'รหัสผ่านไม่ตรงกัน', 'စကားဝှက် မကိုက်ညီပါ', 'ລະຫັດຜ່ານບໍ່ກົງກັນ', 'ពាក្យសម្ងាត់មិនត្រូវគ្នា', 'Kata laluan tidak sepadan'),
(21, 'password_is_short', '', 'Password is too short', 'كلمة المرور قصيرة جدا', 'Wachtwoord is te kort', 'Le mot de passe est trop court', 'Das Passwort ist zu kurz', 'Пароль слишком короткий', 'La contraseña es demasiado corta', 'Şifre çok kısa', 'รหัสผ่านสั้นเกินไป', 'စကားဝှက် တိုလွန်းသည်', 'ລະຫັດຜ່ານສັ້ນເກີນໄປ', 'ពាក្យសម្ងាត់ខ្លីពេក', 'Kata laluan terlalu pendek'),
(22, 'reCaptcha_error', '', 'Please Check the re-captcha.', 'يرجى التحقق من إعادة كابتشا.', 'Controleer alstublieft de re-captcha.', 'Vérifiez le re-captcha.', 'Bitte überprüfen Sie das Re-Captcha.', 'Проверьте перехват.', 'Por favor, compruebe la re-captcha.', 'Lütfen yeniden captcha\'yı kontrol edin.', 'โปรดตรวจสอบ re-captcha', 'ကျေးဇူးပြု၍ re-captcha ကိုစစ်ဆေးပါ။', 'ກະລຸນາກວດສອບ re-captcha.', 'សូមពិនិត្យមើល re-captcha ។', 'Sila semak re-captcha.');



INSERT INTO `langs` (`id`, `lang_key`, `type`, `english`, `arabic`, `dutch`, `french`, `german`, `russian`, `spanish`, `turkish`, `thai`, `burmese`, `lao`, `khmer`, `malay`) VALUES
(54, 'log_out', '', 'Log out', 'الخروج', 'Uitloggen', 'Connectez - Out', 'Ausloggen', 'Выйти', 'Cerrar sesión', 'Çıkış Yap', 'ออกจากระบบ', 'ထွက်ရန်', 'ອອກຈາກລະບົບ', 'ចេញពីគណនី', 'Log keluar'),
(55, 'featured_video', '', 'Featured video', 'فيديو متميز', 'Aanbevolen video', 'Vidéo en vedette', 'Empfohlenes Video', 'Продвигаемое Видео', 'Vídeo destacado', 'Öne çıkan video', 'วิดีโอแนะนำ', 'ပြသထားသော ဗီဒီယို', 'ວິດີໂອທີ່ແນະນຳ', 'វីដេអូពិសេស', 'Video pilihan'),
(56, 'subscribe', '', 'Subscribe', 'الاشتراك', 'abonneren', 'Souscrire', 'Abonnieren', 'Подписывайся', 'Suscribir', 'Abone ol', 'สมัครรับข้อมูล', 'စာရင်းသွင်းရန်', 'ສະໝັກຮັບຂໍ້ມູນ', 'ជាវ', 'Langgan'),
(57, 'views', '', 'Views', 'المشاهدات', 'Bekeken', 'Vues', 'Ansichten', 'Просмотры', 'vistas', 'Görünümler', 'จำนวนการดู', 'ကြည့်ရှုမှုများ', 'ຈຳນວນຜູ້ເຂົ້າເບິ່ງ', 'ចំនួនមើល', 'Tontonan'),
(58, 'save', '', 'Save', 'حفظ', 'Save', 'sauvegarder', 'sparen', 'Сохранить', 'Salvar', 'Kayıt etmek', 'บันทึก', 'သိမ်းဆည်းရန်', 'ບັນທຶກ', 'រក្សាទុក', 'Simpan'),
(59, 'share', '', 'Share', 'شارك', 'Delen', 'Partager', 'Aktie', 'Поделиться', 'Compartir', 'Pay', 'แชร์', 'မျှဝေပါ။', 'ແບ່ງປັນ', 'ចែករំលែក', 'Kongsi'),
(60, 'embed', '', 'Embed', 'تضمين', 'insluiten', 'Intégrer', 'Einbetten', 'встраивать', 'Empotrar', 'gömmek', 'ฝัง', 'ထည့်သွင်းရန်', 'ຝັງ', 'បញ្ចូល', 'Benamkan');
